### ISSUE TITLE
Suggested Improvements. 

### ISSUE THREAD

**Issue by Kingwolf123** [callofduty4x/cod4x-docs#3]
1- Should we move the cod4x-server repo wiki info to the gitbook docs? Why split things.
2- It also has the doxygen produced api-docs, which i would like to see in the docs(with much more detail of course)
3- And what about a more detailed server setup coverage, with information about many of the not-so well known features that cod4x provides etc. The wiki has this, but we should expand it somewhat.
4- We should provide docs/links for useful resources such as plugins(such as mysql) and popular mods for cod4x, such as new experience and threads on the forums.

**Comment by D4edalus** [comment]
1- it is in a separate repo because commits to it pollute the git history and that makes it harder to have an overview of actual code edits when debugging. i guess we will hook it in as a submodule at some point
2- doxygen is planned, read the open issues

its not like im done yet with writing docs. feel free to extend the docs with pull-requests.

**Comment by Kingwolf123** [comment]
1- What i meant is that the [wiki](https://github.com/callofduty4x/CoD4x_Server/wiki) docs should be moved here. Im not asking why this repo is not part of the server repo.
2-Ok.
3- A overview of what you guys are planning would be nice, mabye i could help with some small stuff.

**Comment by D4edalus** [comment]
ah that wiki, maybe some parts, havent looked at it yet. most stuff in there is pretty crappy.
so far i just started writing - and what you see is what i came up with. i will just extend it with topics covering the most frequent topics asked on the forum i guess. 
one thing i want to add for example is how to install the client, that there is an autoinstaller, and if that doesnt work have instructions to install it manually.

EDIT: proof reading, correcting errors and rephrasing where things arent clear helps too.
